# Site settings
title: "Jonghwan's CV"
description: ""

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "김종환"
resume_title:                   ""

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kjhweb@outlook.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "010)6730-4938"
#resume_contact_address:         ""

#resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>• 경험분야 : 데이터 엔지니어링 · 웹 플랫폼개발 · 전자서명 · 데이터 사이언스 · RAG(LLM)</p><p>• 전공 : Business Analytics (석사) / Computer Science (학사)</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/alciakng"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/kjhweb/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
